popup_agreed:
  value: "<h2>Thank you for accepting cookies</h2>\r\n\r\n<p>You can now hide this message or find out more about cookies.</p>\r\n"
popup_agree_button_message: Hyväksy
popup_more_info_button_message: Lisätietoja
popup_find_more_button_message: Lisätietoja
popup_hide_button_message: Piilossa
popup_info:
  value: "<h2>Hel.fi uses cookies&nbsp;</h2>\r\n\r\n<p>We use essential cookies on our website to make the site work. Also third party cookies are used if you give us your permission.</p>\r\n"
popup_link: /node/1
disagree_button_label: 'Ei kiitos'
withdraw_message:
  value: "<h2>Hel.fi uses cookies</h2>\r\n\r\n<p>You have given your consent for us to set cookies.</p>\r\n"
withdraw_tab_button_label: Tietosuoja-asetukset
save_preferences_button_label: 'Tallenna asetukset'
accept_all_categories_button_label: 'Hyväksy kaikki evästeet'
