footer_settings:
  footer_top_content:
    value: "<p><a href=\"#\">Hae yhteystietoja ja numeroita</a></p>\r\n\r\n<p><a class=\"hds-button hds-button--secondary hdbt-icon hdbt-icon--phone\" data-design=\"hds-button hds-button--secondary\" data-icon=\"phone\" data-link-text=\"Helsinki-info 09 310 1691\" data-protocol=\"false\" href=\"#\"><span class=\"hds-button__label\">Helsinki-info 09 310 1691</span></a></p>\r\n"
    format: full_html
  footer_top_title: Yhteystiedot
site_settings: {  }
