label: Siirtovahti
confirm_success_title: "Siirtovahdin tilaus onnistui"
confirm_success_body: "Saat tiedon uusista osumista korkeintaan kerran päivässä.\nVoit perua tilauksen linkillä, jonka saat jokaisen ilmoituksen mukana.\nVoit koska tahansa tilata uuden Siirtovahdin. Siirtovahti on voimassa 12 kuukautta."
confirm_failure_title: "Siirtovahdin vahvistus epäonnistui"
confirm_failure_body: "Siirtovahdin vahvistus epäonnistui. Voit kokeilla vahvistaa Siirtovahdin uudelleen."
already_confirmed_title: "Siirtovahti on jo vahvistettu"
already_confirmed_body: "Olet jo vahvistanut tämän Siirtovahdin.\nSaat tiedon uusista osumista korkeintaan kerran päivässä.\nVoit perua tilauksen linkillä, jonka saat jokaisen ilmoituksen mukana. Voit koska tahansa tilata uuden Siirtovahdin."
renew_success_title: "Siirtovahdin tilauksen jatkaminen onnistui"
renew_success_body: "Siirtovahtisi tilausta on jatkettu."
renew_failure_title: "Siirtovahdin tilauksen jatkaminen epäonnistui"
renew_failure_body: "Siirtovahdin tilauksen jatkaminen epäonnistui. Yritä uudelleen."
unsubscribe_success_title: "Siirtovahti on poistettu"
unsubscribe_success_body: "Siirtovahti on nyt poistettu.\nVoit koska tahansa tilata uuden Siirtovahdin."
unsubscribe_not_found_title: "Siirtovahtia ei löytynyt"
unsubscribe_not_found_body: "Siirtovahtia ei löytynyt. Se on ehkä jo poistettu."
unsubscribe_failure_title: "Siirtovahdin poistaminen epäonnistui"
unsubscribe_failure_body: "Siirtovahdin poistaminen epäonnistui.\nVoit kokeilla poistaa Siirtovahdin uudelleen."
confirm_processing_title: "Siirtovahtia aktivoidaan"
confirm_processing_message: "Siirtovahtia aktivoidaan, odota hetki."
renew_processing_title: "Siirtovahdin tilauksen jatkaminen"
renew_processing_message: "Siirtovahdin tilausta jatketaan, odota hetki."
unsubscribe_processing_title: "Siirtovahtia poistetaan"
unsubscribe_processing_message: "Siirtovahtia poistetaan, odota hetki. Jos olet tehnyt muita siirtovahteja kaupungin verkkosivustolla, tämä ei poista niitä."
