version: '3.7'

services:
  robo:
    image: ghcr.io/city-of-helsinki/drupal-robo:latest
    tty: true
    volumes:
      - .:/app:delegated
    networks:
      - internal
      - stonehenge-network
    dns:
      - 127.0.0.11
    depends_on:
      - app
  app:
    build:
      context: docker/local
      dockerfile: Dockerfile.ci
