version: '3.7'

services:
  robo:
    image: ghcr.io/city-of-helsinki/drupal-robo:latest
    tty: true
    volumes:
      - .:/app:delegated
    networks:
      - internal
      - stonehenge-network
  app:
    build:
      context: docker/local
      dockerfile: Dockerfile.ci
