version: '3.7'

services:
  robo:
    image: ghcr.io/city-of-helsinki/drupal-robo:latest
    shm_size: '2gb'
    tty: true
    volumes:
      - .:/app:delegated
    networks:
      - internal
      - stonehenge-network
    depends_on:
      - app
    extra_hosts:
      - "${DRUPAL_HOSTNAME}:host-gateway"
      - "varnish-${DRUPAL_HOSTNAME}:host-gateway"
  app:
    image: druidfi/drupal:8.0-web
