display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Verkställ
  latest_news:
    display_title: 'Senaste nyheterna'
    display_options:
      title: 'Senaste nyheterna'
      use_more_text: 'Se alla nyheter'
      link_url: /nyheter
