<?php

/**
 * @file
 * Contains alterations for helfi_kymp_migrations module.
 */

declare(strict_types=1);

/**
 * Implements hook_modules_installed().
 */
function helfi_kymp_migrations_modules_installed($modules) : void {
  // Run taxonomy migrations after the necessary entities have been installed.
  if (in_array('helfi_kymp_migrations', $modules)) {
    helfi_kymp_migrations__run_taxonomy_migration();
    \Drupal::state()->set('helfi_kymp_migrations.parent_district_migration_complete', TRUE);
  }
}

/**
 * Run taxonomy migrations.
 */
function helfi_kymp_migrations__run_taxonomy_migration() : void {
  $logger = \Drupal::service('logger.channel.default');
  $migration = \Drupal::service(
    'helfi_kymp_migrations.taxonomy_migration_service'
  );

  try {
    $migration->migrate();
  }
  catch (\Exception $e) {
    $logger->error('HELfi KYMP Migration taxonomy migration failed with error: ' . $e->getMessage());
  }
}
