_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
mode: simple
ignored_config_entities:
  - 'easy_breadcrumb.settings:home_segment_title'
  - 'hdbt_admin_tools.site_settings:footer_settings'
  - 'hdbt_admin_tools.site_settings:site_settings'
  - 'system.site:page.front'
