_core:
  default_config_hash: 6Ka3T1c-CIjEUO1Q64NXKksLthkMhj53a6zy4RJBtkc
verbose: 1
types:
  crop: {  }
  file: {  }
  menu_link_content: {  }
  node:
    '*': '*'
  paragraphs_library_item:
    '*': '*'
  path_alias: {  }
  redirect: {  }
  taxonomy_term:
    '*': '*'
  user: {  }
  paragraph: {  }
  tpr_service_channel: {  }
  tpr_errand_service: {  }
  tpr_ontology_word_details: {  }
  tpr_service:
    '*': '*'
  tpr_unit:
    '*': '*'
  media: {  }
types_translation_lock: {  }
types_js_lock: {  }
form_op_lock:
  crop:
    mode: 0
    values: {  }
  file:
    mode: null
    values: {  }
  menu_link_content:
    mode: 0
    values: {  }
  node:
    mode: 0
    values: {  }
  paragraphs_library_item:
    mode: 0
    values: {  }
  path_alias:
    mode: 0
    values: {  }
  redirect:
    mode: 0
    values: {  }
  taxonomy_term:
    mode: 0
    values: {  }
  user:
    mode: 0
    values: {  }
  paragraph:
    mode: 0
    values: {  }
  tpr_service_channel:
    mode: 0
    values: {  }
  tpr_errand_service:
    mode: 0
    values: {  }
  tpr_ontology_word_details:
    mode: 0
    values: {  }
  tpr_service:
    mode: 0
    values: {  }
  tpr_unit:
    mode: 0
    values: {  }
  media:
    mode: 0
    values: {  }
