monitoring:
  paths:
    patterns: ''
    negate: false
phpAgent:
  status: false
privacy:
  track_user: false
rumAgent:
  serviceName: ''
  serviceVersion: ''
  serverUrl: ''
  status: false
tags:
  path_patterns: ''
  route_patterns: ''
  user_role: false
_core:
  default_config_hash: qeeo_c3WkzY40K-cd44kSfElcm_5q2O6b3oUasH9Xnw
