track_enabled_base_fields: false
local_task_enabled_entity_types:
  - paragraphs_library_item
usage_controller_items_per_page: 25
_core:
  default_config_hash: dsJEXT6TwE7EnEgdtZKLq4XYaUIH2D8WXwnpzKzW1JU
edit_warning_message_entity_types:
  - paragraphs_library_item
delete_warning_message_entity_types:
  - paragraphs_library_item
