_core:
  default_config_hash: OgPHnjkIjDn42IHAwLRXhNzdhX825gq2SrlYKw4kbQ8
langcode: en
path_to_json: /themes/contrib/hdbt/src/icons/editor-selectable-icons.json
site_settings:
  default_icon: home-smoke
  theme_color: tram
  koro: vibration
footer_settings:
  footer_color: dark
