features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
_core:
  default_config_hash: K2gkzwu6yIWvdJgOBpqqGsIB4ZKLNNMvAJsWn-v5iOI
