features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
favicon:
  use_default: 1
enable_darkmode: 0
preset_accent_color: light_blue
accent_color: ''
preset_focus_color: gin
focus_color: ''
high_contrast_mode: 0
classic_toolbar: horizontal
icon_default: 1
icon_upload: ''
_core:
  default_config_hash: WMetmjQwIi1pjKuESDGJxM52cshpFeIifaq7NsDxw3Y
