_core:
  default_config_hash: 30AOZRgOGRJ3m13eg7y-Hzj653nUuoTmsRA2qfsrmtQ
langcode: en
openai_models:
  - text-embedding-3-large
openai_model_pricing:
  text-embedding-3-large: 0.13
ignored_classes:
  - is-hidden
  - visually-hidden
  - skip-link
  - table-of-contents
  - component--recommendations
  - component--map
  - component--hearings
  - announcement
  - content-tags
  - content-date
  - content-links
  - block--askem
