front_page_title: 'Urban environment and traffic'
asset_path: liikenne-assets
prefixes:
  en: urban-environment-and-traffic
  fi: kaupunkiymparisto-ja-liikenne
  sv: stadsmiljo-och-trafik
  ru: urban-environment-and-traffic
  zxx: urban-environment-and-traffic
