_core:
  default_config_hash: kO5fDGTDu1JqYpxKrtzjdzwObU2Ko_3CxABNjqBbYos
attributes:
  icon:
    label: ''
  class:
    label: ''
    description: ''
  target:
    label: ''
    description: ''
    options:
      _blank: 'New window (_blank)'
      _self: 'Same window (_self)'
    default_value: ''
  container_class:
    label: 'Container class(es)'
    description: 'CSS class for the menu list item (&lt;li&gt;). Separate multiple classes by space.'
