entity_type_groups:
  tpr_service:
    tpr_service:
      basic: basic
      open_graph: open_graph
      twitter_cards: twitter_cards
  tpr_unit:
    tpr_unit:
      basic: basic
      open_graph: open_graph
      twitter_cards: twitter_cards
  node:
    article:
      basic: basic
      open_graph: open_graph
      twitter_cards: twitter_cards
    landing_page:
      basic: basic
      open_graph: open_graph
      twitter_cards: twitter_cards
    page:
      basic: basic
      open_graph: open_graph
      twitter_cards: twitter_cards
_core:
  default_config_hash: wsVBmS2iVB6unElbxVQ5TNIUtuMFOAVd6KZqzHGhuqc
