_core:
  default_config_hash: Ne69dMMwlFhwkLqsxAPs20dQCSMk3iibq1pr5qrHf2I
enabled_entity_types:
  - user
  - tpr_service
  - tpr_unit
punctuation:
  hyphen: 1
verbose: false
separator: '-'
max_length: 255
max_component_length: 100
transliterate: true
reduce_ascii: false
case: true
ignore_words: ''
update_action: 2
safe_tokens:
  - alias
  - path
  - join-path
  - login-url
  - url
  - url-brief
  - menu-link-parents
