_core:
  default_config_hash: fFCOUWimqdj2E7qYCcYmI2LH7rwpaLEUOfi69hUFuXk
max_links: 10000
cron_generate: true
cron_generate_interval: 24
generate_duration: 10000
remove_duplicates: true
skip_untranslated: true
disable_language_hreflang: false
xsl: false
base_url: ''
default_variant: default
custom_links_include_images: false
excluded_languages: {  }
enabled_entity_types:
  - node
  - menu_link_content
  - tpr_service
  - tpr_unit
entities_per_queue_item: 100
