_core:
  default_config_hash: t5W6QbLZA8s7VAoHDDldhRB2Emm1blOGOOKHMV855Gk
token: 130476e797ca4a07a3bd030c6dbf7ed0
domain_plugin_id: siteimprovedomain_simple
prepublish_enabled: true
api_username: ''
api_key: ''
enabled_content_types: {  }
enabled_taxonomies: {  }
