<?php

/**
 * @file
 * Contains alterations for config.
 */

declare(strict_types=1);

use Drupal\config_rewrite\ConfigRewriterInterface;

/**
 * Implements hook_rewrite_config_update().
 */
function helfi_kymp_config_rewrite_config_update(string $module, ConfigRewriterInterface $configRewriter): void {
  $modules = [
    'helfi_node_announcement',
    'helfi_node_news_item',
    'helfi_paragraphs_accordion',
    'helfi_paragraphs_banner',
    'helfi_paragraphs_image',
    'helfi_paragraphs_list_of_links',
    'helfi_paragraphs_popular_services',
    'helfi_paragraphs_remote_video',
    'helfi_paragraphs_sidebar_text',
    'helfi_paragraphs_text',
  ];

  if (in_array($module, $modules)) {
    // Rewrite module configuration.
    $configRewriter->rewriteModuleConfig('helfi_kymp_config');
  }
}
