footer_settings:
  footer_top_title: 'Ta kontakt'
  footer_top_content:
    value: "<p><a class=\"link\" data-design=\"link\" data-link-text=\"Helsingfors-info\" data-protocol=\"false\" href=\"https://www.hel.fi/kanslia/neuvonta-sv/\">Helsingfors-info</a></p>\r\n\r\n<p><a class=\"link\" data-design=\"link\" data-link-text=\"Sök kontaktuppgifter och telefonnummer\" data-protocol=\"false\" href=\"https://numerot.hel.fi/\">Sök kontaktuppgifter och telefonnummer</a></p>\r\n\r\n<p><a class=\"link\" data-design=\"link\" data-link-text=\"Ge respons\" data-protocol=\"false\" href=\"https://www.hel.fi/respons/\">Ge respons</a></p>\r\n"
    format: full_html
