label: Fordonsflytt
confirm_success_title: "Beställningen av Flyttningsvakten lyckades"
confirm_success_body: "Du får information om nya träffar högst en gång om dagen.\nDu kan avsluta din beställning via en länk som finns i varje meddelande.\nDu kan när som helst beställa en ny Flyttningsvakt. Flyttningsvakten är i kraft i 12 månader."
confirm_failure_title: "Beställningen av Flyttningsvakten misslyckades"
confirm_failure_body: "Beställningen av Flyttningsvakten misslyckades. Du kan försöka bekräfta Flyttningsvakten på nytt."
already_confirmed_title: "Flyttningsvakten har redan bekräftats"
already_confirmed_body: "Du har redan bekräftat Flyttningsvakten.\nDu får information om nya träffar högst en gång om dagen.\nDu kan avsluta din beställning via en länk som finns i varje meddelande. Du kan när som helst beställa en ny Flyttningsvakt."
renew_success_title: "Flyttningsvakten förnyades"
renew_success_body: "Din Flyttningsvakten har förnyats."
renew_failure_title: "Flyttningsvakten förnyades inte"
renew_failure_body: "Det gick inte att förnya Flyttningsvakten. Försök på nytt."
unsubscribe_success_title: "Flyttningsvakten har raderats"
unsubscribe_success_body: "Flyttningsvakten är nu raderad.\nDu kan när som helst beställa en ny Flyttningsvakt."
unsubscribe_not_found_title: "Flyttningsvakten hittades inte"
unsubscribe_not_found_body: "Flyttningsvakten hittades inte. Den kan redan ha tagits bort."
unsubscribe_failure_title: "Raderingen av Flyttningsvakten misslyckades"
unsubscribe_failure_body: "Raderingen av Flyttningsvakten misslyckades.\nDu kan försöka radera Flyttningsvakten på nytt."
confirm_processing_title: "Aktiverar Flyttningsvakten"
confirm_processing_message: "Vänligen vänta medan Flyttningsvakten aktiveras."
renew_processing_title: "Förnyar Flyttningsvakten"
renew_processing_message: "Vänta medan Flyttningsvakten förnyas."
unsubscribe_processing_title: "Tar bort Flyttningsvakten"
unsubscribe_processing_message: "Vänligen vänta medan Flyttningsvakten tas bort. Om du har skapat andra flyttningsvakter på stadens webbplats tar denna åtgärd inte bort dem."
