#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Define the hdbt_subtheme path relative to the Git root
SUBTHEME_DIR="public/themes/custom/hdbt_subtheme/src"

# Check if any staged file is inside the hdbt_subtheme
if git diff --cached --name-only | grep -q "^$SUBTHEME_DIR"; then
  echo "Detected changes in hdbt_subtheme/src/, running lint..."
  cd "$SUBTHEME_DIR" || exit 1
  npm run lint
fi
