on:
  push:
    branches:
      - dev
name: Automatic release PR
jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request
        run: |
          gh pr create \
            --base main \
            --head dev \
            --title "Dev to main" \
            --body "Dev to main" \
            --label automation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
