on:
  repository_dispatch:
    types: [config_change]
name: Update config
env:
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"
  SIMPLETEST_DB: "mysql://drupal:drupal@db:3306/drupal"
jobs:
  update-config:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/city-of-helsinki/drupal-php-docker:8.0

    services:
      db:
        image: druidfi/db:mysql5.7-drupal
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Download latest dump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run download -n latest.sql

      - name: Build project
        run: |
          composer install
          $(drush sql:connect) < latest.sql
          drush cr && drush cim -y
          composer update drupal/helfi_platform_config
          drush updb -y
          drush cex -y

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          committer: GitHub <noreply@github.com>
          author: actions-bot <actions-bot@users.noreply.github.com>
          commit-message: Update configuration
          title: Update active configuration
          body: |
            - Updated active configuration.

              Auto-generated by [create-pull-request][1]
              [1]: https://github.com/peter-evans/create-pull-request
          branch: update-configuration
